# Generated by Django 6.1.1 on 2026-09-23 19:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='产线名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='产线编号')),
                ('foreman', models.CharField(blank=True, max_length=30, verbose_name='线长(师傅化名)')),
                ('capacity', models.PositiveIntegerField(default=100, verbose_name='日产能(件)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '产线',
                'verbose_name_plural': '产线',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30, unique=True, verbose_name='订单编号')),
                ('product', models.CharField(max_length=80, verbose_name='产品名称')),
                ('customer', models.CharField(blank=True, max_length=50, verbose_name='客户(脱敏)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量(件)')),
                ('work_hours', models.FloatField(default=0, verbose_name='总工时估算(小时)')),
                ('due_date', models.DateField(verbose_name='交期')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, '低'), (2, '普通'), (3, '高'), (4, '紧急')], default=2, verbose_name='优先级')),
                ('status', models.CharField(choices=[('pending', '待排产'), ('scheduled', '已排产'), ('producing', '生产中'), ('done', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-priority', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='工序名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='工序编号')),
                ('seq', models.PositiveIntegerField(default=1, verbose_name='工序顺序')),
                ('std_hours', models.FloatField(default=1.0, verbose_name='单件标准工时(小时)')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='board.line', verbose_name='所属产线')),
            ],
            options={
                'verbose_name': '工序',
                'verbose_name_plural': '工序',
                'ordering': ['line__code', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='计划开始')),
                ('end_time', models.DateTimeField(verbose_name='计划结束')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='进度(%)')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='board.line', verbose_name='产线')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='board.order', verbose_name='订单')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='board.process', verbose_name='工序')),
            ],
            options={
                'verbose_name': '排产计划',
                'verbose_name_plural': '排产计划',
                'ordering': ['line__code', 'start_time'],
            },
        ),
    ]
