# Generated by Django 6.1.1 on 2026-09-23 19:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(blank=True, max_length=30, verbose_name='报工人(师傅化名)')),
                ('shift', models.CharField(choices=[('day', '早班'), ('mid', '中班'), ('night', '晚班')], default='day', max_length=10, verbose_name='班次')),
                ('qty_ok', models.PositiveIntegerField(default=0, verbose_name='合格数(件)')),
                ('qty_ng', models.PositiveIntegerField(default=0, verbose_name='不良数(件)')),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='采集时间')),
                ('source', models.CharField(choices=[('quick', '快速录入'), ('manual', '台账录入'), ('import', '批量导入')], default='quick', max_length=10, verbose_name='录入方式')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='board.line', verbose_name='产线')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='board.order', verbose_name='订单')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='board.process', verbose_name='工序')),
            ],
            options={
                'verbose_name': '报工记录',
                'verbose_name_plural': '报工记录',
                'ordering': ['-logged_at', '-id'],
            },
        ),
    ]
